function [design] = getInstructions(keys, design, participantInfo)
% getInstructions: is called and contains all instructions for the subject
%   input:
%       design - struct containing information about experimental design,
%       like number of runs, trials and durations
%   output:
%       design - updating the design input struct with instructions
if nargin < 2 || isempty(design)
    design = struct;
end
% design
if ~isfield(design, 'stimulusPresentationTime')
    design.stimulusPresentationTime = 1;
end
if ~isfield(design, 'ITI')
    design.ITI = 10;
end
if ~isfield(participantInfo, 'language')
    participantInfo.language = 'english';
end

if strcmp (participantInfo.language, 'german')
    if keys.house  == keys.left
        leftImage = 'Haus';
        rightImage = 'Gesicht';
    else
        leftImage = 'Gesicht';
        rightImage = 'Haus';
    end
    %% general instructions
    design.Introduction = [
        'Vielen Dank, dass du an unserer Binocular Rivalry Studie teilnimmst.\n\n'...
        'Drücke eine beliebige Taste um fortzufahren.'
        ];
    design.cueInstruction = [
        'Jedes trial beginnt mit einem kurzen cue, bestehend aus einem \n' ...
        'Buchstaben (P, A, I oder +) und einem eingefärbten Fixationskreuz\n\n'...
        'Das bedeuten die Farben:\n'
    ];
    design.taskInstruction = [
        'Deine Aufgabe ist es, von dem angezeigten Buchstaben abhängig \n' ...
        'eines dieser vier Sachen zu machen:\n\n'...
        'P - das angezeigte Bild ansehen                                                          \n'...
        'A - dich in dem kombinierten Bild auf Haus oder Gesicht konzentrieren,\n' ...
        '    abhängig vom cue.\n'...
        'I - dir auf der grauen Fläche das Haus oder Gesicht vorstellen,            \n' ...
        '    abhängig von cue.\n'...
        '+ - das Fixationskreuz fixieren.                                                              \n\n'...
        'Drücke eine beliebige Taste, um fortzufahren'
        ];
    design.reportInstructionReport = [
        'Danach werden deinen Augen zwei unterschiedliche Bilder gezeigt.\n\n' ...
        'Gib an, welches Bild du *zuerst* wahrgenommen hast:\n\n' ...
        'Für ' leftImage ' drücke links\n' ...
        'Für ' rightImage ' drücke rechts\n\n' ...
        'Falls du keines deutlicher wahrgenommen hast als das andere drücke keine Taste\n\n'...
        'Drücke eine beliebige Taste, um fortzufahren'
    ];
    design.reportInstructionNoReport = [
        'Danach werden deinen Augen zwei unterschiedliche Bilder gezeigt.\n\n' ...
        'Fixiere den Fixationspunkt mit deinen Augen.\n' ...
        'Dieser kann an einer von 8 Positionen sein.\n' ...
        'Solltest du zwei Fixationspunkte gleichzeitig sehen, fixiere das Kreuz in der Mitte des Bildes.\n\n'...
        'Drücke eine beliebige Taste, um fortzufahren'
        ];
    design.reportInstructionDual = [
        'Danach werden deinen Augen zwei unterschiedliche Bilder gezeigt.\n\n' ...
        'Gib an, welches Bild du *zuerst* wahrgenommen hast:\n\n' ...
        'Für ' leftImage ' drücke links\n' ...
        'Für ' rightImage ' drücke rechts\n\n' ...
        'Fixiere zusätzlich den Fixationspunkt mit deinen Augen.\n' ...
        'Dieser kann an einer von 8 Positionen sein.\n' ...
        'Solltest du zwei Fixationspunkte gleichzeitig sehen, fixiere das Kreuz in der Mitte des Bildes.\n\n'...
        'Drücke eine beliebige Taste, um fortzufahren'
        ];
    design.questionInstruction = [
        'Danach wirst du auf einer Skala von 1-5 gefragt, wie gut du die Aufgabe\n'...
        'in diesem Trial erledigt hast.\n'...
        '1 - nicht gut \n'...
        'bis\n'...
        '5 - sehr gut \n\n'...
        'Drücke eine beliebige Taste, um fortzufahren'
    ];
    design.legendReminderInstructionReport = [
        'Erinnerung:\n'...
        'Für ' leftImage ' drücke links\n' ...
        'Für ' rightImage ' drücke rechts\n\n' ...
        'Das bedeuten die Farben:\n'
        ];
    design.legendReminderInstructionNoReport = [
        'Erinnerung:\n'...
        'Für ' leftImage ' drücke links\n' ...
        'Für ' rightImage ' drücke rechts\n\n' ...
        'Das bedeuten die Farben:\n'
        ];
    % fixation cross
    design.fixOnFixCross = [
        'Zwischen den Trials fixiere bitte das Fixationskreuz.\n\n' ...
        'Drücke einen beliebige Taste um fortzufahren.'
        ];
    design.waitTillStart = [
        'Wir starten in ' num2str(round(design.waitTillStartDuration)) 's.\n\n'
        ];

    design.RunIsOver = [
        'Der Durchlauf ist vorbei.\n\n' ...
        'Drücke eine beliebige Taste und wende dich an den Versuchsleiter.'
        ];

    %% Onset Training messages
    design.OnsetInstructionsOnsetTraining = [
      'Wir beginnen mit ein paar Übungsdurchläufen.\n\n'...
      'Drücke eine beliebige Taste um fortzufahren.'
    ];

    design.OnsetInstructionsOnsetTrainingEnd = [
      'Die Übungsdurchläufe sind abgeschlossen\n' ...
      'und das Hauptexperiment beginnt.\n\n'...
      'Drücke eine beliebige Taste um fortzufahren.'
    ];

    %% Consent Form
    design.consent = [
        'Hiermit bestätige ich, dass:\n' ...
        'Ich über die Studie und den Versuchsablauf aufgeklärt worden bin.\n' ...
        'Ich willige ein, an dieser Studie über visuelle Wahrnehmung,\n' ...
        'Sofern ich Fragen zu dieser vorgesehenen Studie hatte, wurden sie\n' ...
        'vom Versuchsleitenden vollständig und zu meiner Zufriedenheit beantwortet.\n\n' ...
        'Drücke eine beliebige Taste um zu bestätigen.'
        ];

    design.cueTextPerception = ['P'];
    design.cueTextAttention = ['A'];
    design.cueTextImagery = ['I'];
    design.cueTextBaseline = ['+'];
    %design.finalQuestion = ['Wie gut haben Sie die Aufgabe erledigt?'];
    design.finalQuestion = [' 1 - 5?'];
else
    % Key assignment
    if keys.house  == keys.left
        leftImage = 'house';
        rightImage = 'face';
    else
        leftImage = 'face';
        rightImage = 'house';
    end
%% general instructions
    design.Introduction = [
        'Thank you for participating in our Binocular Rivalry study.\n\n'...
        'Press any key to continue.'
        ];
    design.cueInstruction = [
        'Each trial begins with a short cue consisting of a \n' ...
        'letter (P, A, I, or +) and a colored fixation cross.\n\n' ...
        'The colors mean the following:\n'
        ];

    design.taskInstruction = [
        'Depending on the letter shown, your task is to do one of the \n' ...
        'following four things:\n\n' ...
        'P - look at the image shown                                        \n' ...
        'A - focus on the house or face in the combined image, \n' ...
        '    depending on the cue.\n' ...
        'I - imagine the house or face on the gray background,\n' ...
        '    depending on the cue.\n' ...
        '+ - fixate on the fixation cross.                                     \n\n' ...
        'Press any key to continue'
        ];

    design.reportInstructionReport = [
        'You will then be shown two different images.\n\n' ...
        'Indicate which image you perceived *first*:\n\n' ...
        'For ' leftImage ' press left\n' ...
        'For ' rightImage ' press right\n\n' ...
        'If you did not perceive either image more clearly than the other, do not press any key.\n\n' ...
        'Press any key to continue'
        ];

    design.reportInstructionNoReport = [
        'You will then be shown two different images.\n\n' ...
        'Fixate on the fixation point with your eyes.\n' ...
        'It can appear at one of 8 positions.\n' ...
        'If you see two fixation points at the same time, fixate on the cross in the center of the image.\n\n' ...
        'Press any key to continue'
        ];

    design.reportInstructionDual = [
        'You will then be shown two different images.\n\n' ...
        'Indicate which image you perceived *first*:\n\n' ...
        'For ' leftImage ' press left\n' ...
        'For ' rightImage ' press right\n\n' ...
        'Additionally, fixate on the fixation point with your eyes.\n' ...
        'It can appear at one of 8 positions.\n' ...
        'If you see two fixation points at the same time, fixate on the cross in the center of the image.\n\n' ...
        'Press any key to continue'
        ];

    design.questionInstruction = [
        'You will then be asked to rate on a scale from 1-5 how well you \n' ...
        'performed the task in this trial.\n' ...
        '1 - not well \n' ...
        'to\n' ...
        '5 - very well \n\n' ...
        'Press any key to continue'
        ];

    design.legendReminderInstructionReport = [
        'Reminder:\n' ...
        'For ' leftImage ' press left\n' ...
        'For ' rightImage ' press right\n\n' ...
        'The colors mean the following:\n'
        ];

    design.legendReminderInstructionNoReport = [
        'Reminder:\n' ...
        'For ' leftImage ' press left\n' ...
        'For ' rightImage ' press right\n\n' ...
        'The colors mean the following:\n'
        ];

    % fixation cross
    design.fixOnFixCross = [
        'Between the trials, please fixate on the fixation cross.\n\n' ...
        'Press any key to continue.'
        ];
    design.waitTillStart = [
        'We will start in ' num2str(round(design.waitTillStartDuration)) 's.\n\n'
        ];

    design.RunIsOver = [
        'The run is over.\n\n' ...
        'Press any key and contact the experimenter.'
        ];
    
    %% Onset Training
    design.OnsetInstructionsOnsetTraining = [
        'We will start with a few practice trials.\n\n' ...
        'Press any key to continue.'
    ];

    design.OnsetInstructionsOnsetTrainingEnd = [
        'The practice trials are complete,\n' ...
        'and the main experiment is about to begin.\n\n' ...
        'Press any key to continue.'
    ];

     %% Consent Form
    design.consent = [
         'I hereby confirm that:\n' ...
        'I have been informed about the study and the test procedure.\n' ...
        'I agree to participate in this study on visual perception,\n' ...
        'Any questions I had about this planned study were\n' ...
        'answered fully and to my satisfaction by the study leader.\n\n' ...
        'Press any key to confirm.'
        ];

    design.cueTextPerception = ['P'];
    design.cueTextAttention = ['A'];
    design.cueTextImagery = ['I'];
    design.cueTextBaseline = ['+'];
    %design.finalQuestion = ['How well did you work on the task?'];
    design.finalQuestion = [' 1 - 5?'];

end
end
